### Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the powerof N - i - 1.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [10]:
def vander(onedarr,N,increasing = False):
    if increasing:
        return np.array([onedarr**i for i in range(N)]).T
    return np.array([onedarr**i for i in range(N-1,-1,-1)]).T


In [11]:
vander(arr,5,True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]], dtype=int32)

## Question: Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:
arr1 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [19]:
def moving_average(arr,k):
    n = len(arr)
    result = []
    for i in range(n-k+1):
        sum = 0
        for j in range(k):
            sum+=arr[i+j]
        result.append(sum/k)
    return np.array(result)

In [22]:
moving_average(arr1,2)

array([  4. ,   6. ,   4.5,   5. ,   9. ,  10.5,  38. ,  68.5,  76.5,
        90. ,  99.5, 125. ])

In [23]:
moving_average(arr1,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])